version: "3.8"
services:
  database:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - postgres-network
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    container_name: backend
    image: backend:1.0
    build:
      context: ./backEnd
      dockerfile: Dockerfile
    ports:
      - 5050:5000
    networks:
      - postgres-network
    volumes:
      - ./backEnd:/app
    depends_on:
      - database
    command: ["yarn", "start"]
  web:
    container_name: frontend
    image: frontend:1.0
    build:
      context: ./frontEnd
      dockerfile: Dockerfile
    ports:
      - 2020:80
    volumes:
      - ./frontEnd:/app
    depends_on:
      - backend
    command: ["nginx", "-g", "daemon off;"]

networks:
  postgres-network:
    driver: bridge
